services:
  dns-sni-proxy:
    build: .
    container_name: dns-sni-proxy
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "80:80"
      - "443:443"
    # No cap_add needed since we run as root in the container
    environment:
      SINK_IPV4: "203.0.113.10"   # <- set to your server's public IPv4
      # SINK_IPV6: "2001:db8::10" # optional IPv6
      DNS_UPSTREAM: "1.1.1.1"
      ALLOWLIST: "example.com,corp.internal"
      LOG_LEVEL: "INFO"