services:
  dns-sink:
    build: ./dns-sink
    container_name: dns-sink
    restart: unless-stopped
    ports:
      - "5.161.151.125:53:53/udp"  # ← set this
    environment:
      SINK_IPV4: "5.161.151.125"
      DNS_TTL: "30"
      LOG_LEVEL: "INFO"

  sni-proxy:
    image: haproxy:lts
    container_name: sni-proxy
    restart: unless-stopped
    ports:
      - "5.161.151.125:80:80"
      - "5.161.151.125:443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
